// Copyright (EIDA) 2004-2016 Emirates Identity Authority (EIDA)
// email: PKITeam@emiratesid.ae
// All rights reserved.

// The source code is sole property of Emirates Identity Authority, Abu Dhabi, UAE. Even after modifications it is still property of Emirates Identify Authority.
// This source has to be kept in strict confidence and must not be disclosed to any third party in any case.


var NO_ERRORS = 0;
var E_SELECT_ID_APPLICATION = -1;
var E_SELECT_CM_APPLICATION = -2;
var E_SELECT_MOC_APPLICATION = -3;
var E_GET_CARD_SERIAL_NUMBER = -4;
var E_GET_CHIP_SERIAL_NUMBER = -5;
var E_GET_ISSUER_SERIAL_NUMBER = -6;
var E_GET_ISSUER_REFERENCE_NUMBER = -7;
var E_GET_CPLC0101 = -8;
var E_GET_CPLC9F7F = -9;
var E_MOC_GET_MAX_FAILED_MATCH = -10;
var E_MOC_GET_SERIAL_NUMBER = -11;
var E_MOC_GET_APPLET_STATE = -12;
var E_MOC_GET_ALGORITHM_VER = -13;
var E_SM_GET_CHALLENGE = -14;
var E_SM_GET_CIPHERED_PIN = -15;
var E_SELECT_FILEKEY = -17;
var E_SET_USER_AUTH_SE = -18;
var E_SM_CARD_NOT_GENUINE = -19;

var E_PUBLIC_DATA_PUBLIC_KEY = -22;
var E_PUBLIC_DATA_VERIFY_PHOTO = -23;
var E_PUBLIC_DATA_VERIFY_SF3 = -24;
var E_PUBLIC_DATA_VERIFY_SF5 = -25;
var E_MOC_GET_CHALLENGE = -26;
var E_SM_MOC_MUTUAL_AUTHENTICATION = -27;
var E_MOC_MUTUAL_AUTHENTICATION = -28;
var E_MOC_APPLICATION_BLOCKED = -29;
var E_MOC_MUTUAL_AUTHENTICATION_UNKNOWN = -30;

var E_MOC_SESSION_KEYS = -32;
var E_MOC_MATCH_UNKNOWN = -33;
var E_MOC_MATCH_GENERAL = -34;
var E_MOC_MATCH_GENERAL_UNKNOWN = -35;
var E_MOC_GET_BIT_GROUP = -36;
var E_MOC_MATCH_BAD_TEMPLATE = -37;
var E_MOC_MATCH_SEC_STATUS_NOT_SATISFIED = -38;
var E_ID_APPLICATION_VERIFY_CIPHERED_PIN = -39;
var E_ID_APPLICATION_BLOCKED = -40;
var E_ID_APPLICATION_VERIFY_CIPHERED_PIN_UNKNOWN = -41;
var E_ID_GET_FINGERPRINTS = -42;
var E_PKI_SIGN_GENERAL = -43;
var E_PKI_SIGN_PIN_INCORRECT = -44;
var E_PKI_SIGN_PIN_BLOCKED = -45;
var E_PKI_SIGN_SIGNATURE_SIZE_ZERO = -46;
var E_PKI_EXPORT_CERTIFICATE = -47;
var E_PKI_CERTIFICATE_SIZE_ZERO = -48;
var E_PKI_CSP_SIGNING_INIT = -49;
var E_PKI_CSP_SIGNING = -50;
var E_PKI_PIN_LENGTH_INCORRECT = -51;
var E_ID_READ_IDN_CN = -52;
var E_ID_READ_PHOTOGRAPHY = -53;
var E_ID_READ_EF_CardHolderData_SF3 = -54;
var E_ID_READ_EF_CardHolderData_SF5 = -55;
var E_ID_READ_EF_ROOT_CERTIFICATE = -56;
var E_PKI_SESSION_KEYS = -57;
var E_PKI_ENCODE_PIN = -58;
var E_PKI_PIN_VERIFY_GENERAL = -59;
var E_BIOMETRICS_CONVERSION = -60;
var E_BIOMETRICS_OFFCARD_MATCHING = -61;
var E_BIOMETRICS_NO_DEVICE = -62;
var E_BIOMETRICS_CAPTURE_CONVERT = -63;
var E_BIOMETRICS_NO_TEMPLATES = -64;
var E_BIOMETRICS_CAPTURE = -65;
var E_BIOMETRICS_SDK_BAD_LICENSE = -66;
var E_BIOMETRICS_SDK_INIT = -67;
var E_BIOMETRICS_CC_TEMPLATE_TO_ISO = -68;
var E_BIOMETRICS_WRONG_FINGER_INDEX = -69;
var E_PKI_INVALID_PIN = -70;
var E_PKI_INVALID_CARD_VERSION = -71;
var E_PKI_CONSTRUCT_PKI_APDU = -72;
var E_PKI_SET_SIGN_KEY_INDEX = -73;
var E_PKI_ERROR_READ_SIGNATURE = -74;
var E_CHECK_CRYCKS_FAILED = -75;
var E_GET_CRYCKS_FAILED = -76;
var E_DECRYPT_PROTECTED_DATA = -77;

var E_PKI_PIN_VERIFY_SEC_STATUS_NOT_SATISFIED = -80;
var E_PKI_PIN_BLOCKED = -81;
var E_PKI_ADMIN_PIN_BLOCKED = -83;
var E_PKI_PIN_BAD_REFERENCE = -82;
var E_PKI_ADMIN_PIN = -84;
var E_SELECT_PKI_APPLICATION = -85;
var E_PKI_GET_SERIAL_NUMBER = -86;
var E_PKI_GET_CHALLENGE = -87;
var E_SM_PKI_MUTUAL_AUTHENTICATION = -88;
var E_PKI_MUTUAL_AUTHENTICATION = -89;
var E_PKI_APPLICATION_BLOCKED = -90;
var E_PKI_MUTUAL_AUTHENTICATION_UNKNOWN = -91;
var E_PKI_PIN_UNBLOCK_GENERAL = -92;
var E_PKI_PIN_CHANGE_GENERAL = -93;

var E_NULL_ARGUMENT 				= -100;
var E_INVALID_ARGUMENT_VALUE 		= -101;
var E_NOT_SUPPORTED_IMPLEMENTATION 	= -102;

var E_SELECT_FB_APPLICATION = -121;
var E_FB_APPLICATION_VERIFY_CIPHERED_PIN = -122;
var E_FB_APPLICATION_BLOCKED = -123;
var E_FB_APPLICATION_VERIFY_CIPHERED_PIN_UNKNOWN = -124;
var E_RETRIEVING_FAMILY_BOOK_DATA = -125;
var E_FB_READ_FAMILY_HEAD_DATA = -126;
var E_FB_READ_WIFE_DATA = -127;
var E_FB_READ_CHILD_DATA = -128;
var E_FB_VERIFY_FAMILY_HEAD_EF_SIGNATURE = -129;
var E_FB_VERIFY_WIFE_EF_SIGNATURE = -130;
var E_FB_VERIFY_CHILD_EF_SIGNATURE = -131;
var E_FB_HEAD_DATA_INVALID = -132;
var E_ID_ROOT_CERTIFICATE_PARSE = -133;
var E_BIOMETRICS_NOT_SUPPORTED_APPLET = -134;

var E_CLASS_NOT_FOUND = -201;
var E_FIELD_NOT_FOUND = -202;

var E_SM_NOT_INITIALIZED = -300;

var E_SAM_NO_PCSC_READERS = -311;
var E_SAM_INVALID_CONNECTION = -312;
var E_SAM_SELECT_APPLICATION = -313;
var E_SAM_VERIFY_PIN = -314;
var E_SAM_READ_REF_IDS = -315;
var E_SAM_READ_REF_ID_INFO = -316;
var E_SAM_GET_ATR = -317;
var E_SAM_PIN_NULL_OR_INCORRECT = -318;
var E_SAM_ATRS_NULL = -319;

var E_WRONG_PIN_0 = -352;
var E_WRONG_PIN_1 = -353;
var E_WRONG_PIN_2 = -354;
var E_WRONG_PIN_3 = -355;
var E_WRONG_PIN_4 = -356;

var E_HSM_UNABLE_TO_LOAD_CRYPTOKI = -400;
var E_HSM_UNABLE_TO_INITIALIZE_CRYPTOKI = -401;

var E_HSM_GET_SLOT_FAILED = -403;
var E_HSM_OPEN_SESSION_FAILED = -404;
var E_HSM_LOGIN_FAILED = -405;
var E_HSM_KEY_NOT_FOUND = -406;
var E_HSM_INCRYPT_INIT_FAILED = -407;
var E_HSM_INCRYPT_FAILED = -408;
var E_HSM_LOGOUT_FAILED = -409;

var E_ESTABLISH_CONTEXT 			= -1000;
var E_NO_PCSC_READERS				= -1001;
var E_UNKNOWN_ERROR 				= -1002;
var E_REMOTE_SM_ADDRESS_EMPTY 		= -1003;
var E_BIOMETRICS_OFFCARD_MATCHING_FAILED_LOW_SCORE = -1004;
var E_NO_CARDS_PRESENT 				= -1005;
var E_WEB_COMPONENT_NOT_INITIALIZED = -1006;
var E_ERROR_RETRIEVING_PUBLIC_DATA 	= -1007;

var E_SERVER_ERROR 					= -1010;
var E_CARD_EXCEPTION 				= -1011;
var E_GET_CARD_CRYPTOGRAM 			= -1012;
var E_GET_FINGERPRINT_BINARY_DATA 	= -1013;
var E_ENCODE_PIN 					= -1014;
var E_CRYCKS_EXCEPTION 				= -1015;
var E_GET_ATR 						= -1016;
var E_SM_GET_RESET_COMMAND 			= -1017;

var E_VG_INTERNAL_SERVER_ERROR			= -500;
var E_VG_TRANSACTION_NOT_FOUND 			= -501;
var E_VG_TRANSACTION_TYPE_NOT_SET		= -502;
var E_VG_FINGERPRINTS_NULL 				= -503;
var E_VG_IMAGE_PARAMS_INCORRECT 		= -504;
var E_VG_IMAGE_HEIGHT_INCORRECT 		= -505;
var E_VG_IMAGE_WIDTH_INCORRECT 			= -506;
var E_VG_MATCH_FAILED 					= -507;
var E_VG_INVALID_FINGERPRINT_SIGNATURE	= -508;
var E_VG_CARD_CSN_NOT_FOUND				= -509;
var E_VG_NATIONAL_ID_OR_CN_ERROR		= -510;
var E_VG_LOW_MATCH_SCORE				= -511;
var E_VG_CANNOT_BUILD_SIGNED_RESP		= -512;
var E_VG_SM_MODULE_NOT_AVAILABLE		= -513;
var E_VG_CHALLENGE_NULL					= -514;
var E_VG_PARAMS_NULL					= -515;
var E_VG_GENERATE_CIPHERED_PIN_FAILED	= -516;
var E_VG_CARD_STATUS_FAILED				= -517;
var E_VG_CARD_NOT_GENUINE				= -518;
var E_VG_CERTIFICATE_INVALID			= -519;
var E_VG_CERTIFICATE_NOT_YET_VALID		= -520;
var E_VG_CERTIFICATE_EXPIRED			= -521;
var E_VG_CERTIFICATE_STATUS_REVOKED		= -522;
var E_VG_CERTIFICATE_STATUS_UNKNOWN 	= -523;
var E_VG_SIGNATURE_INVALID				= -524;
var E_VG_MOC_GENERATE_SESSION_KEYS_FAILED	= -525;
var E_VG_MOC_MUTUAL_AUTH_FAILED			= -526;
var E_VG_MOC_BUILD_SMCOMMAND_FAILED		= -527;
var E_VG_TRANSACTION_ALREADY_FINALIZED	= -528;
var E_VG_PKI_GENERATE_SESSION_KEYS_FAILED	= -529;
var E_VG_PKI_MUTUAL_AUTH_FAILED			= -530;
var E_VG_DECRYPT_KEY_ERROR				= -531;
var E_VG_DECRYPT_DATA_ERROR				= -532;
var E_VG_PKI_BUILD_SM_COMMAND_FAILED	= -533;
var E_VG_USER_NOT_AUTHENTICATED			= -534;
var E_VG_PKI_BUILD_RESET_COMMAND_FAILED	= -535;
var E_VG_TRANSACTION_NOT_PART_OF_SERVICE	= -536;
var E_VG_SERVICE_NOT_REGISTERED_TO_SERVICEPROVIDER	= -537;
var E_VG_SERVICEPROVIDER_NOT_FOUND	= -538;
var E_VG_NO_SERVICE_ID	= -539;
var E_VG_NO_ACTION	= -540;

var E_VG_DEPRECATED_APPLET = -544;
var E_VG_GENERATE_CIPHERED_PIN_FB_FAILED = -545;

var E_SERVER_RELATIVE_CERT_PATH_NOT_CONFIGURED = -600;
var E_SERVER_CERT_PATH_INVALID = -601;
var E_SERVER_CERT_FILE_INVALID_FORMAT = -602;
var E_REMOTE_SERVER_PATH_NOT_CONFIGURED = -603;
var E_VG_RESPONSE_SIGNATURE_VERIFICATION_FAILED = -604;
var E_VG_RESPONSE_FORMAT_INVALID = -605;
var E_VG_RESPONSE_SIGNING_CERT_EXPIRED_OR_NOT_YET_VALID = -606;
var E_VG_RESPONSE_TRUST_BUILDING_FAILED = -607;
var E_VG_CARD_STATUS_INVALID = -608;

//EF Signature verification
var E_INVALID_PHOTOGRAPHY_EF_SIGNATURE = 620;
var E_INVALID_NON_MODIFIABLE_EF_SIGNATURE = 621;
var E_INVALID_MODIFIABLE_EF_SIGNATURE = 622;
var E_INVALID_HOME_ADDRESS_EF_SIGNATURE = 623;
var E_INVALID_WORK_ADDRESS_EF_SIGNATURE = 624;
 

var E_VG_DEVICE_ALREADY_REGISTERED 	= -206;

var ErrorMessages = new Array();


ErrorMessages[ NO_ERRORS ] = "NO_ERRORS_EXCEPTION_EXCEPTION";

ErrorMessages[ E_VG_DEVICE_ALREADY_REGISTERED ] = "E_VG_DEVICE_ALREADY_REGISTERED_EXCEPTION";

ErrorMessages[ E_SELECT_ID_APPLICATION ] = "E_SELECT_ID_APPLICATION_EXCEPTION_EXCEPTION";
ErrorMessages[ E_SELECT_CM_APPLICATION ] = "E_SELECT_CM_APPLICATION_EXCEPTION_EXCEPTION";
ErrorMessages[ E_SELECT_MOC_APPLICATION ] = "E_SELECT_MOC_APPLICATION_EXCEPTION";
ErrorMessages[ E_GET_CARD_SERIAL_NUMBER ] = "E_GET_CARD_SERIAL_NUMBER_EXCEPTION";
ErrorMessages[ E_GET_CHIP_SERIAL_NUMBER ] = "E_GET_CHIP_SERIAL_NUMBER_EXCEPTION";
ErrorMessages[ E_GET_ISSUER_SERIAL_NUMBER ] = "E_GET_ISSUER_SERIAL_NUMBER_EXCEPTION";
ErrorMessages[ E_GET_ISSUER_REFERENCE_NUMBER ] = "E_GET_ISSUER_REFERENCE_NUMBER_EXCEPTION";
ErrorMessages[ E_GET_CPLC0101 ] = "E_GET_CPLC0101_EXCEPTION";
ErrorMessages[ E_GET_CPLC9F7F ] = "E_GET_CPLC9F7F_EXCEPTION";
ErrorMessages[ E_MOC_GET_MAX_FAILED_MATCH ] = "E_MOC_GET_MAX_FAILED_MATCH_EXCEPTION";
ErrorMessages[ E_MOC_GET_SERIAL_NUMBER ] = "E_MOC_GET_SERIAL_NUMBER_EXCEPTION";
ErrorMessages[ E_MOC_GET_APPLET_STATE ] = "E_MOC_GET_APPLET_STATE_EXCEPTION";
ErrorMessages[ E_MOC_GET_ALGORITHM_VER ] = "E_MOC_GET_ALGORITHM_VER_EXCEPTION";
ErrorMessages[ E_SM_GET_CHALLENGE ] = "E_SM_GET_CHALLENGE_EXCEPTION";
ErrorMessages[ E_SM_GET_CIPHERED_PIN ] = "E_SM_GET_CIPHERED_PIN_EXCEPTION";
ErrorMessages[ E_SELECT_FILEKEY ] = "E_SELECT_FILEKEY_EXCEPTION";
ErrorMessages[ E_SET_USER_AUTH_SE ] = "E_SET_USER_AUTH_SE_EXCEPTION";

ErrorMessages[ E_SM_CARD_NOT_GENUINE ] = "E_SM_CARD_NOT_GENUINE_EXCEPTION";

ErrorMessages[ E_PUBLIC_DATA_PUBLIC_KEY ] = "E_PUBLIC_DATA_PUBLIC_KEY_EXCEPTION";
ErrorMessages[ E_PUBLIC_DATA_VERIFY_PHOTO ] = "E_PUBLIC_DATA_VERIFY_PHOTO_EXCEPTION";
ErrorMessages[ E_PUBLIC_DATA_VERIFY_SF3 ] = "E_PUBLIC_DATA_VERIFY_SF3_EXCEPTION";
ErrorMessages[ E_PUBLIC_DATA_VERIFY_SF5 ] = "E_PUBLIC_DATA_VERIFY_SF5_EXCEPTION";

ErrorMessages[ E_MOC_GET_CHALLENGE ] = "E_MOC_GET_CHALLENGE_EXCEPTION";
ErrorMessages[ E_SM_MOC_MUTUAL_AUTHENTICATION ] = "E_SM_MOC_MUTUAL_AUTHENTICATION_EXCEPTION";
ErrorMessages[ E_MOC_MUTUAL_AUTHENTICATION ] = "E_MOC_MUTUAL_AUTHENTICATION_EXCEPTION";



ErrorMessages[ E_MOC_APPLICATION_BLOCKED ] = "E_MOC_APPLICATION_BLOCKED_EXCEPTION";
ErrorMessages[ E_MOC_MUTUAL_AUTHENTICATION_UNKNOWN ] = "E_MOC_MUTUAL_AUTHENTICATION_UNKNOWN_EXCEPTION";
ErrorMessages[ E_MOC_SESSION_KEYS ] = "E_MOC_SESSION_KEYS_EXCEPTION";

ErrorMessages[ E_MOC_MATCH_UNKNOWN ] = "E_MOC_MATCH_UNKNOWN_EXCEPTION";
ErrorMessages[ E_MOC_MATCH_GENERAL ] = "E_MOC_MATCH_GENERAL_EXCEPTION";
ErrorMessages[ E_MOC_MATCH_GENERAL_UNKNOWN ] = "E_MOC_MATCH_GENERAL_UNKNOWN_EXCEPTION";
ErrorMessages[ E_MOC_GET_BIT_GROUP ] = "E_MOC_GET_BIT_GROUP_EXCEPTION";
ErrorMessages[ E_MOC_MATCH_BAD_TEMPLATE ] = "E_MOC_MATCH_BAD_TEMPLATE_EXCEPTION";
ErrorMessages[ E_MOC_MATCH_SEC_STATUS_NOT_SATISFIED ] = "E_MOC_MATCH_SEC_STATUS_NOT_SATISFIED_EXCEPTION";

ErrorMessages[ E_ID_APPLICATION_VERIFY_CIPHERED_PIN ] = "E_ID_APPLICATION_VERIFY_CIPHERED_PIN_EXCEPTION";
ErrorMessages[ E_ID_APPLICATION_BLOCKED ] = "E_ID_APPLICATION_BLOCKED_EXCEPTION";
ErrorMessages[ E_ID_APPLICATION_VERIFY_CIPHERED_PIN_UNKNOWN ] = "E_ID_APPLICATION_VERIFY_CIPHERED_PIN_UNKNOWN_EXCEPTION";

ErrorMessages[ E_ID_GET_FINGERPRINTS ] = "E_ID_GET_FINGERPRINTS_EXCEPTION";

ErrorMessages[ E_PKI_SIGN_GENERAL ] = "E_PKI_SIGN_GENERAL_EXCEPTION";

ErrorMessages[ E_PKI_SIGN_PIN_INCORRECT ] = "E_PKI_SIGN_PIN_INCORRECT_EXCEPTION";
ErrorMessages[ E_PKI_SIGN_PIN_BLOCKED ] = "E_PKI_SIGN_PIN_BLOCKED_EXCEPTION";
ErrorMessages[ E_PKI_SIGN_SIGNATURE_SIZE_ZERO ] = "E_PKI_SIGN_SIGNATURE_SIZE_ZERO_EXCEPTION";

ErrorMessages[ E_PKI_EXPORT_CERTIFICATE ] = "E_PKI_EXPORT_CERTIFICATE_EXCEPTION";
ErrorMessages[ E_PKI_CERTIFICATE_SIZE_ZERO ] = "E_PKI_CERTIFICATE_SIZE_ZERO_EXCEPTION";
ErrorMessages[ E_PKI_CSP_SIGNING_INIT ] = "E_PKI_CSP_SIGNING_INIT_EXCEPTION";
ErrorMessages[ E_PKI_CSP_SIGNING ] = "E_PKI_CSP_SIGNING_EXCEPTION";
ErrorMessages[ E_PKI_PIN_LENGTH_INCORRECT ] = "E_PKI_PIN_LENGTH_INCORRECT_EXCEPTION";
ErrorMessages[ E_ID_READ_IDN_CN ] = "E_ID_READ_IDN_CN_EXCEPTION";
ErrorMessages[ E_ID_READ_PHOTOGRAPHY ] = "E_ID_READ_PHOTOGRAPHY_EXCEPTION";
ErrorMessages[ E_ID_READ_EF_CardHolderData_SF3 ] = "E_ID_READ_EF_CardHolderData_SF3_EXCEPTION";
ErrorMessages[ E_ID_READ_EF_CardHolderData_SF5 ] = "E_ID_READ_EF_CardHolderData_SF5_EXCEPTION";

ErrorMessages[ E_PKI_SESSION_KEYS ] = "E_PKI_SESSION_KEYS_EXCEPTION";
ErrorMessages[ E_PKI_ENCODE_PIN ] = "E_PKI_ENCODE_PIN_EXCEPTION";
ErrorMessages[ E_PKI_PIN_VERIFY_GENERAL ] = "E_PKI_PIN_VERIFY_GENERAL_EXCEPTION";

ErrorMessages[ E_BIOMETRICS_CONVERSION ] = "E_BIOMETRICS_CONVERSION_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_OFFCARD_MATCHING ] = "E_BIOMETRICS_OFFCARD_MATCHING_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_NO_DEVICE ] = "E_BIOMETRICS_NO_DEVICE_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_CAPTURE_CONVERT ] = "E_BIOMETRICS_CAPTURE_CONVERT_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_NO_TEMPLATES ] = "E_BIOMETRICS_NO_TEMPLATES_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_CAPTURE ] = "E_BIOMETRICS_CAPTURE_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_SDK_BAD_LICENSE ] = "E_BIOMETRICS_SDK_BAD_LICENSE_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_SDK_INIT ] = "E_BIOMETRICS_SDK_INIT_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_CC_TEMPLATE_TO_ISO ] = "E_BIOMETRICS_CC_TEMPLATE_TO_ISO_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_WRONG_FINGER_INDEX ] = "E_BIOMETRICS_WRONG_FINGER_INDEX_EXCEPTION";

ErrorMessages[ E_PKI_INVALID_PIN ] = "E_PKI_INVALID_PIN_EXCEPTION";
ErrorMessages[ E_PKI_INVALID_CARD_VERSION ] = "E_PKI_INVALID_CARD_VERSION_EXCEPTION";
ErrorMessages[ E_PKI_CONSTRUCT_PKI_APDU ] = "E_PKI_CONSTRUCT_PKI_APDU_EXCEPTION";
ErrorMessages[ E_PKI_SET_SIGN_KEY_INDEX ] = "E_PKI_SET_SIGN_KEY_INDEX_EXCEPTION";
ErrorMessages[ E_PKI_ERROR_READ_SIGNATURE ] = "E_PKI_ERROR_READ_SIGNATURE_EXCEPTION";

ErrorMessages[ E_CHECK_CRYCKS_FAILED ] = "E_CHECK_CRYCKS_FAILED_EXCEPTION";
ErrorMessages[ E_GET_CRYCKS_FAILED ] = "E_GET_CRYCKS_FAILED_EXCEPTION";
ErrorMessages[ E_DECRYPT_PROTECTED_DATA ] = "E_DECRYPT_PROTECTED_DATA_EXCEPTION";

ErrorMessages[ E_PKI_PIN_VERIFY_SEC_STATUS_NOT_SATISFIED ] = "E_PKI_PIN_VERIFY_SEC_STATUS_NOT_SATISFIED_EXCEPTION";
ErrorMessages[ E_PKI_PIN_BLOCKED ] = "E_PKI_PIN_BLOCKED_EXCEPTION";
ErrorMessages[ E_PKI_ADMIN_PIN_BLOCKED ] = "E_PKI_ADMIN_PIN_BLOCKED_EXCEPTION";
ErrorMessages[ E_PKI_PIN_BAD_REFERENCE ] = "E_PKI_PIN_BAD_REFERENCE_EXCEPTION";
ErrorMessages[ E_PKI_ADMIN_PIN ] = "E_PKI_ADMIN_PIN_EXCEPTION";
ErrorMessages[ E_SELECT_PKI_APPLICATION ] = "E_SELECT_PKI_APPLICATION_EXCEPTION";
ErrorMessages[ E_PKI_GET_SERIAL_NUMBER ] = "E_PKI_GET_SERIAL_NUMBER_EXCEPTION";
ErrorMessages[ E_PKI_GET_CHALLENGE ] = "E_PKI_GET_CHALLENGE_EXCEPTION";
ErrorMessages[ E_SM_PKI_MUTUAL_AUTHENTICATION ] = "E_SM_PKI_MUTUAL_AUTHENTICATION_EXCEPTION";
ErrorMessages[ E_PKI_MUTUAL_AUTHENTICATION ] = "E_PKI_MUTUAL_AUTHENTICATION_EXCEPTION";
ErrorMessages[ E_PKI_APPLICATION_BLOCKED ] = "E_PKI_APPLICATION_BLOCKED_EXCEPTION";
ErrorMessages[ E_PKI_MUTUAL_AUTHENTICATION_UNKNOWN ] = "E_PKI_MUTUAL_AUTHENTICATION_UNKNOWN_EXCEPTION";
ErrorMessages[ E_PKI_PIN_UNBLOCK_GENERAL ] = "E_PKI_PIN_UNBLOCK_GENERAL_EXCEPTION";

ErrorMessages[ E_PKI_PIN_CHANGE_GENERAL ] = "E_PKI_PIN_CHANGE_GENERAL_EXCEPTION";

ErrorMessages[ E_NULL_ARGUMENT ] = "E_NULL_ARGUMENT_EXCEPTION";
ErrorMessages[ E_INVALID_ARGUMENT_VALUE ] =  "E_INVALID_ARGUMENT_VALUE_EXCEPTION";
ErrorMessages[ E_NOT_SUPPORTED_IMPLEMENTATION ] = "E_NOT_SUPPORTED_IMPLEMENTATION_EXCEPTION";


ErrorMessages[ E_CLASS_NOT_FOUND ] = "E_CLASS_NOT_FOUND_EXCEPTION";
ErrorMessages[ E_FIELD_NOT_FOUND ] = "E_FIELD_NOT_FOUND_EXCEPTION";


ErrorMessages[ E_SM_NOT_INITIALIZED ] = "E_SM_NOT_INITIALIZED_EXCEPTION";

ErrorMessages[ E_SAM_NO_PCSC_READERS ] = "E_SAM_NO_PCSC_READERS_EXCEPTION";
ErrorMessages[ E_SAM_INVALID_CONNECTION ] = "E_SAM_INVALID_CONNECTION_EXCEPTION";
ErrorMessages[ E_SAM_SELECT_APPLICATION ] = "E_SAM_SELECT_APPLICATION_EXCEPTION";
ErrorMessages[ E_SAM_VERIFY_PIN ] = "E_SAM_VERIFY_PIN_EXCEPTION";
ErrorMessages[ E_SAM_READ_REF_IDS ] = "E_SAM_READ_REF_IDS_EXCEPTION";
ErrorMessages[ E_SAM_READ_REF_ID_INFO ] = "E_SAM_READ_REF_ID_INFO_EXCEPTION";
ErrorMessages[ E_SAM_GET_ATR ] = "E_SAM_GET_ATR_EXCEPTION";
ErrorMessages[ E_SAM_PIN_NULL_OR_INCORRECT ] = "E_SAM_PIN_NULL_OR_INCORRECT_EXCEPTION";
ErrorMessages[ E_SAM_ATRS_NULL ] = "E_SAM_ATRS_NULL_EXCEPTION";


ErrorMessages[ E_WRONG_PIN_0 ] = "E_WRONG_PIN_0_TRIALS_REMAINING_EXCEPTION";
ErrorMessages[ E_WRONG_PIN_1 ] = "E_WRONG_PIN_1_TRIALS_REMAINING_EXCEPTION";
ErrorMessages[ E_WRONG_PIN_2 ] = "E_WRONG_PIN_2_TRIALS_REMAINING_EXCEPTION";
ErrorMessages[ E_WRONG_PIN_3 ] = "E_WRONG_PIN_3_TRIALS_REMAINING_EXCEPTION";
ErrorMessages[ E_WRONG_PIN_4 ] = "E_WRONG_PIN_4_TRIALS_REMAINING_EXCEPTION";


ErrorMessages[ E_HSM_UNABLE_TO_LOAD_CRYPTOKI ] = "E_HSM_UNABLE_TO_LOAD_CRYPTOKI_EXCEPTION";
ErrorMessages[ E_HSM_UNABLE_TO_INITIALIZE_CRYPTOKI ] = "E_HSM_UNABLE_TO_INITIALIZE_CRYPTOKI_EXCEPTION";
ErrorMessages[ E_HSM_GET_SLOT_FAILED ] = "E_HSM_GET_SLOT_FAILED_EXCEPTION";
ErrorMessages[ E_HSM_OPEN_SESSION_FAILED ] = "E_HSM_OPEN_SESSION_FAILED_EXCEPTION";
ErrorMessages[ E_HSM_LOGIN_FAILED ] = "E_HSM_LOGIN_FAILED_EXCEPTION";
ErrorMessages[ E_HSM_KEY_NOT_FOUND ] = "E_HSM_KEY_NOT_FOUND_EXCEPTION";
ErrorMessages[ E_HSM_INCRYPT_INIT_FAILED ] = "E_HSM_INCRYPT_INIT_FAILED_EXCEPTION";
ErrorMessages[ E_HSM_INCRYPT_FAILED ] = "E_HSM_INCRYPT_FAILED_EXCEPTION";
ErrorMessages[ E_HSM_LOGOUT_FAILED ] = "E_HSM_LOGOUT_FAILED_EXCEPTION";


ErrorMessages[ E_UNKNOWN_ERROR ] = "E_UNKNOWN_ERROR_EXCEPTION";
ErrorMessages[ E_ESTABLISH_CONTEXT ] = "Error establishing PCSC context.";
ErrorMessages[ E_NO_PCSC_READERS ]	 = "No PC/SC card readers found.";
ErrorMessages[ E_NO_CARDS_PRESENT ]	 = "Please insert a card.";
ErrorMessages[ E_WEB_COMPONENT_NOT_INITIALIZED ] = "Web component is not initialized";
ErrorMessages[ E_ERROR_RETRIEVING_PUBLIC_DATA ]	= "Can not retrieve public data";

ErrorMessages[ E_REMOTE_SM_ADDRESS_EMPTY ] = "E_REMOTE_SM_ADDRESS_EMPTY_EXCEPTION";
ErrorMessages[ E_BIOMETRICS_OFFCARD_MATCHING_FAILED_LOW_SCORE ] = "E_BIOMETRICS_OFFCARD_MATCHING_FAILED_LOW_SCORE_EXCEPTION";

    ErrorMessages[ E_SELECT_FB_APPLICATION ] = "E_SELECT_FB_APPLICATION_EXCEPTION";
    ErrorMessages[ E_FB_APPLICATION_VERIFY_CIPHERED_PIN ] ="E_FB_APPLICATION_VERIFY_CIPHERED_PIN_EXCEPTION";
    ErrorMessages[ E_FB_APPLICATION_BLOCKED ] ="E_FB_APPLICATION_BLOCKED_EXCEPTION";
    ErrorMessages[ E_FB_APPLICATION_VERIFY_CIPHERED_PIN_UNKNOWN ]= "E_FB_APPLICATION_VERIFY_CIPHER_PIN_UNKNOWN_EXCEPTION";
    ErrorMessages[ E_RETRIEVING_FAMILY_BOOK_DATA ] ="E_RETRIEVING_FB_DATA_EXCEPTION";

    ErrorMessages[ E_FB_READ_FAMILY_HEAD_DATA ]= "E_FB_FAMILY_HEAD_DATA_EXCEPTION";
    ErrorMessages[ E_FB_READ_WIFE_DATA ] ="E_FB_WIFE_DATA_EXCEPTION";
    ErrorMessages[ E_FB_READ_CHILD_DATA ] ="E_FB_CHILD_DATA_EXCEPTION";

    ErrorMessages[ E_FB_VERIFY_FAMILY_HEAD_EF_SIGNATURE ] ="E_FB_FAMILY_HEAD_DATA_SIGNATURE_VERIFICATION_EXCEPTION";
    ErrorMessages[ E_FB_VERIFY_WIFE_EF_SIGNATURE ] ="E_FB_WIFE_DATA_SIGNATURE_VERIFICATION_EXCEPTION";
    ErrorMessages[ E_FB_VERIFY_CHILD_EF_SIGNATURE ] ="E_FB_CHILD_DATA_SIGNATURE_VERIFICATION_EXCEPTION";
    ErrorMessages[ E_FB_HEAD_DATA_INVALID ] ="E_FB_FAMILY_HEAD_DATA_INVALID_EXCEPTION";

	ErrorMessages[ E_ID_READ_EF_ROOT_CERTIFICATE ] ="E_ID_READ_EF_ROOT_CERTIFICATE_EXCEPTION";
	ErrorMessages[ E_ID_ROOT_CERTIFICATE_PARSE ] ="E_ID_ROOT_CERTIFICATE_PARSE_EXCEPTION";
	ErrorMessages[ E_BIOMETRICS_NOT_SUPPORTED_APPLET ] ="E_BIOMETRICS_NOT_SUPPORTED_APPLET_EXCEPTION";

ErrorMessages[ E_SERVER_ERROR ] = "E_SERVER_ERROR_EXCEPTION";
ErrorMessages[ E_CARD_EXCEPTION ] = "E_CARD_EXCEPTION_EXCEPTION";
ErrorMessages[ E_GET_CARD_CRYPTOGRAM ] = "E_GET_CARD_CRYPTOGRAM_EXCEPTION";
ErrorMessages[ E_GET_FINGERPRINT_BINARY_DATA ] = "E_GET_FINGERPRINT_BINARY_DATA_EXCEPTION";
ErrorMessages[ E_ENCODE_PIN ] = "E_ENCODE_PIN_EXCEPTION";
ErrorMessages[ E_CRYCKS_EXCEPTION ] = "E_CRYCKS_EXCEPTION_EXCEPTION";
ErrorMessages[ E_GET_ATR ] = "E_GET_ATR_EXCEPTION";
ErrorMessages[ E_SM_GET_RESET_COMMAND ] = "E_SM_GET_RESET_COMMAND_EXCEPTION";

ErrorMessages[ E_VG_INTERNAL_SERVER_ERROR] = "E_VG_INTERNAL_SERVER_ERROR";
ErrorMessages[ E_VG_TRANSACTION_NOT_FOUND]			= "E_VG_TRANSACTION_NOT_FOUND";
ErrorMessages[ E_VG_TRANSACTION_TYPE_NOT_SET]		= "E_VG_TRANSACTION_TYPE_NOT_SET";
ErrorMessages[ E_VG_FINGERPRINTS_NULL]				= "E_VG_FINGERPRINTS_NULL";
ErrorMessages[ E_VG_IMAGE_PARAMS_INCORRECT] 		= "E_VG_IMAGE_PARAMS_INCORRECT";
ErrorMessages[ E_VG_IMAGE_HEIGHT_INCORRECT] 		= "E_VG_IMAGE_HEIGHT_INCORRECT";
ErrorMessages[ E_VG_IMAGE_WIDTH_INCORRECT]			= "E_VG_IMAGE_WIDTH_INCORRECT";
ErrorMessages[ E_VG_MATCH_FAILED]					= "E_VG_MATCH_FAILED";
ErrorMessages[ E_VG_INVALID_FINGERPRINT_SIGNATURE]	= "E_VG_INVALID_FINGERPRINT_SIGNATURE";
ErrorMessages[ E_VG_CARD_CSN_NOT_FOUND]				= "E_VG_CARD_CSN_NOT_FOUND";
ErrorMessages[ E_VG_NATIONAL_ID_OR_CN_ERROR]		= "E_VG_NATIONAL_ID_OR_CN_ERROR";
ErrorMessages[ E_VG_LOW_MATCH_SCORE]				= "E_VG_LOW_MATCH_SCORE";
ErrorMessages[ E_VG_CANNOT_BUILD_SIGNED_RESP]		= "E_VG_CANNOT_BUILD_SIGNED_RESP";
ErrorMessages[ E_VG_SM_MODULE_NOT_AVAILABLE]		= "E_VG_SM_MODULE_NOT_AVAILABLE";
ErrorMessages[ E_VG_CHALLENGE_NULL]					= "E_VG_CHALLENGE_NULL";
ErrorMessages[ E_VG_PARAMS_NULL]					= "E_VG_PARAMS_NULL";
ErrorMessages[ E_VG_GENERATE_CIPHERED_PIN_FAILED]	= "E_VG_GENERATE_CIPHERED_PIN_FAILED";
ErrorMessages[ E_VG_CARD_STATUS_FAILED]				= "E_VG_CARD_STATUS_FAILED";
ErrorMessages[ E_VG_CARD_NOT_GENUINE]				= "E_VG_CARD_NOT_GENUINE";
ErrorMessages[ E_VG_CERTIFICATE_INVALID]			= "E_VG_CERTIFICATE_INVALID";
ErrorMessages[ E_VG_CERTIFICATE_NOT_YET_VALID]		= "E_VG_CERTIFICATE_NOT_YET_VALID";
ErrorMessages[ E_VG_CERTIFICATE_EXPIRED]			= "E_VG_CERTIFICATE_EXPIRED";
ErrorMessages[ E_VG_CERTIFICATE_STATUS_REVOKED]		= "E_VG_CERTIFICATE_STATUS_REVOKED";
ErrorMessages[ E_VG_CERTIFICATE_STATUS_UNKNOWN]		= "E_VG_CERTIFICATE_STATUS_UNKNOWN";
ErrorMessages[ E_VG_SIGNATURE_INVALID]				= "E_VG_SIGNATURE_INVALID";
ErrorMessages[ E_VG_MOC_GENERATE_SESSION_KEYS_FAILED]	= "E_VG_MOC_GENERATE_SESSION_KEYS_FAILED";
ErrorMessages[ E_VG_MOC_MUTUAL_AUTH_FAILED]			= "E_VG_MOC_MUTUAL_AUTH_FAILED";
ErrorMessages[ E_VG_MOC_BUILD_SMCOMMAND_FAILED]		= "E_VG_MOC_BUILD_SMCOMMAND_FAILED";
ErrorMessages[ E_VG_TRANSACTION_ALREADY_FINALIZED]	= "E_VG_TRANSACTION_ALREADY_FINALIZED";
ErrorMessages[ E_VG_PKI_GENERATE_SESSION_KEYS_FAILED]	= "E_VG_PKI_GENERATE_SESSION_KEYS_FAILED";
ErrorMessages[ E_VG_PKI_MUTUAL_AUTH_FAILED]			= "E_VG_PKI_MUTUAL_AUTH_FAILED";
ErrorMessages[ E_VG_DECRYPT_KEY_ERROR]				= "E_VG_DECRYPT_KEY_ERROR";
ErrorMessages[ E_VG_DECRYPT_DATA_ERROR]				= "E_VG_DECRYPT_DATA_ERROR";
ErrorMessages[ E_VG_PKI_BUILD_SM_COMMAND_FAILED]	= "E_VG_PKI_BUILD_SM_COMMAND_FAILED";
ErrorMessages[ E_VG_USER_NOT_AUTHENTICATED]			= "E_VG_USER_NOT_AUTHENTICATED";
ErrorMessages[ E_VG_PKI_BUILD_RESET_COMMAND_FAILED]	= "E_VG_PKI_BUILD_RESET_COMMAND_FAILED";
ErrorMessages[ E_VG_TRANSACTION_NOT_PART_OF_SERVICE	]= "E_VG_TRANSACTION_NOT_PART_OF_SERVICE";
ErrorMessages[ E_VG_SERVICE_NOT_REGISTERED_TO_SERVICEPROVIDER ] = "E_VG_SERVICE_NOT_REGISTERED_TO_SERVICEPROVIDER";
ErrorMessages[ E_VG_SERVICEPROVIDER_NOT_FOUND ]	= "E_VG_SERVICEPROVIDER_NOT_FOUND";
ErrorMessages[ E_VG_NO_SERVICE_ID ]	= "E_VG_NO_SERVICE_ID";
ErrorMessages[ E_VG_NO_ACTION ]	= "E_VG_NO_ACTION";

ErrorMessages[ E_VG_DEPRECATED_APPLET ]	= "E_VG_DEPRECATED_APPLET";
ErrorMessages[ E_VG_GENERATE_CIPHERED_PIN_FB_FAILED ]	= "E_VG_GENERATE_CIPHER_PIN_FB_FAILED";

///
ErrorMessages[E_SERVER_RELATIVE_CERT_PATH_NOT_CONFIGURED]	= "E_SERVER_RELATIVE_CERT_PATH_NOT_CONFIGURED";
ErrorMessages[ E_SERVER_CERT_PATH_INVALID ]	= "E_SERVER_CERT_PATH_INVALID";
ErrorMessages[ E_SERVER_CERT_FILE_INVALID_FORMAT ]	= "E_SERVER_CERT_FILE_INVALID_FORMAT";
ErrorMessages[ E_REMOTE_SERVER_PATH_NOT_CONFIGURED ]	= "E_REMOTE_SERVER_PATH_NOT_CONFIGURED";
ErrorMessages[ E_VG_RESPONSE_SIGNATURE_VERIFICATION_FAILED ]	= "E_VG_RESPONSE_SIGNATURE_VERIFICATION_FAILED";
ErrorMessages[ E_VG_RESPONSE_FORMAT_INVALID ]	= "E_VG_RESPONSE_FORMAT_INVALID";
ErrorMessages[ E_VG_RESPONSE_SIGNING_CERT_EXPIRED_OR_NOT_YET_VALID ]	= "E_VG_RESPONSE_SIGNING_CERT_EXPIRED_OR_NOT_YET_VALID";
ErrorMessages[ E_VG_RESPONSE_TRUST_BUILDING_FAILED ]	= "E_VG_RESPONSE_TRUST_BUILDING_FAILED";
ErrorMessages[ E_VG_CARD_STATUS_INVALID ]	= "E_VG_CARD_STATUS_INVALID";

ErrorMessages[ E_INVALID_PHOTOGRAPHY_EF_SIGNATURE] = "E_INVALID_PHOTOGRAPHY_EF_SIGNATURE";
ErrorMessages[ E_INVALID_NON_MODIFIABLE_EF_SIGNATURE] = "E_INVALID_NON_MODIFIABLE_EF_SIGNATURE";
ErrorMessages[ E_INVALID_MODIFIABLE_EF_SIGNATURE] = "E_INVALID_MODIFIABLE_EF_SIGNATURE";
ErrorMessages[ E_INVALID_HOME_ADDRESS_EF_SIGNATURE] = "E_INVALID_HOME_ADDRESS_EF_SIGNATURE";
ErrorMessages[ E_INVALID_WORK_ADDRESS_EF_SIGNATURE] = "E_INVALID_WORK_ADDRESS_EF_SIGNATURE";


function GetErrorMessage(Code)
{
	errorMessage = ErrorMessages[Code];
	if(errorMessage == undefined)
		errorMessage = "Error : "+Code;
		
	return errorMessage;	
}

function ProcessError(Ret)
{
	// process the error code here to get the message to display
	// for now just display the error code
	alert(GetErrorMessage(Ret));

}

String.prototype.startsWith = function(str)
{return (this.match("^"+str)==str)}
